# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Veysi ADIN
tagline:          'Know thyself'
description:      'Master Student - Junior Embedded Systems Engineer'
url:              http://hyde.getpoole.com
baseurl:          https://veysiadn.github.io/about-me/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/veysiadn/about-me

theme: jekyll-theme-cayman
